name: Deploy Next.js to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22

          script: |
            cd /var/www/html/abdallah-company
            git pull origin master
            npm install
            npm run build
            pm2 restart abdallah-company
